### ISSUE TITLE
CSS Workaround for pointless scrollbar

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/tess_atlas_webbuilder#4]
CSS Workaround:

```css
.bd-sidebar-primary div#rtd-footer-container {
    bottom:-1rem;
    margin:-1rem;
    position:fixed;
}
```

_Originally posted by @thtrummer in https://github.com/executablebooks/sphinx-book-theme/issues/732#issuecomment-1752572223_
